# Generated by Django 4.2.3 on 2024-02-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_timeentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeEntry',
        ),
    ]
